// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    //url: process.env["DATABASE_URL"],
    url: process.env["postgresql://postgres.tgasbyyxotwjvvouftkp:[Toycharn191145]@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres"],
  },
});
